name: "build"

on:
  push:
    branches: [ develop, master, new]
  pull_request:
    branches: [ develop, master ]

jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login do docker.io
        run: docker login -u abhay900 -p abhay12
      - name: build and publish image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./distribution/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: abhay900/seata:latest        
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 8, 11 ]
        os: [ ubuntu-18.04 ]
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v2.3.4

      # step 2
      - name: "Set up Java JDK"
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      # step 3
      - name: "Set up ENV"
        # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        run: if [ "${{ matrix.java }}" == "8" ]; then
                echo "IMAGE_NAME=openjdk:8u212-jre-alpine" >> $GITHUB_ENV;
             elif [ "${{ matrix.java }}" == "11" ]; then
                echo "IMAGE_NAME=openjdk:11-jre-stretch"   >> $GITHUB_ENV;
             fi

      # step 4
      - name: "Build with Maven"
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        # https://docs.github.com/cn/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        run: if [ "${{matrix.java}}" == "8" ] && [ "${{github.event_name}}" == "push" ] && [ "${{github.ref}}" == "refs/heads/develop" ]; then
               ./mvnw -T 4C clean install -DskipTests=false -Dcheckstyle.skip=false -Dlicense.skip=false -P image -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
             else
               ./mvnw -T 4C clean install -DskipTests=false -Dcheckstyle.skip=false -Dlicense.skip=false          -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
             fi

      # step 5
      - name: "Codecov"
        if: matrix.java == '8'
        uses: codecov/codecov-action@v1.5.0
