name: "build"

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
jobs:

  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Install and Build Maven
        run: |
           docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
           arm64v8/ubuntu:20.04 \
           bash -exc 'apt-get update -y && \
           apt-get install openjdk-8-jdk -y && \
           apt-get install maven -y && \
           mvn clean compile -Dcheckstyle.skip=true'                  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login do docker.io
        run: docker login -u abhay900 -p abhay12
      - name: build and publish image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./distribution/Dockerfile
          platforms: linux/amd64
          push: true
          tags: abhay900/seata:latest

