name: Test

on: [push, pull_request]
jobs:
  test_arm64: 
     runs-on: ubuntu-latest
     strategy:
      matrix:
        java: [8]
      fail-fast: false
     steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Install and Run tests
        run: |
               docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
               arm64v8/ubuntu:20.04 \
               bash -exc 'apt-get update -y && \
                apt-get install openjdk-8-jdk -y && \
                export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64 && \
                export PATH=$PATH:$JAVA_HOME/bin && \
                echo $PATH && \
                apt-get install maven -y && \
                mvn clean compile -Dcheckstyle.skip=true'
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
        springboot: [2.6.4,2.5.10,2.5.13]
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v2.3.4

      # step 2
      - name: "Set up Java JDK"
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      # step 3
      - name: "Test with Maven"
        # https://docs.github.com/cn/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        run: if [ "${{ matrix.java }}" == "8" ]; then
            ./mvnw -T 4C clean install -e                      -Dspring-boot.version=${{ matrix.springboot }} -DskipTests=false -Dcheckstyle.skip=false -Dlicense.skip=false -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
          else
            ./mvnw -T 4C clean install -e -P args-for-un-java8 -Dspring-boot.version=${{ matrix.springboot }} -DskipTests=false -Dcheckstyle.skip=false -Dlicense.skip=false -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
          fi
